### ISSUE TITLE
GH Pages do not deploy when using GITHUB_TOKEN

### ISSUE THREAD

**Issue by MrManicotti** [mhausenblas/mkdocs-deploy-gh-pages#1]
The site is published to gh-pages as expected, but the build of the site itself is not performed due to authorization being performed with GITHUB_TOKEN rather than personal token.  
  
This will however work for private repositories.

**Comment by mhausenblas** [comment]
@MrManicotti thanks a lot for raising this issue and right on! I did experience something similar and was wondering, alright. Do you maybe have a solution that would work in the general case, can you PR it?

**Comment by MrManicotti** [comment]
Details defined [here](https://github.com/peaceiris/actions-gh-pages/blob/master/README.md)

### (1) Add SSH deploy key

Generate your deploy key with the following command.

```sh
ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
# You will get 2 files:
#   gh-pages.pub (public key)
#   gh-pages     (private key)
```

Next, Go to **Repository Settings**

- Go to **Deploy Keys** and add your public key with the **Allow write access**
- Go to **Secrets** and add your private key as `ACTIONS_DEPLOY_KEY`


   
***
I'm not quite sure how to make this change myself. I'm not aware currently where the action is even *written* as all I see are the docker file and the shell script the docker file runs. For this case you'd basically just do checking for *is ssh given? If not, github_token*, and use one env var but not the other when performing the push.

**Comment by mhausenblas** [comment]
Gotcha, thanks @MrManicotti!

> I'm not aware currently where the action is even written as all I see are the docker file and the shell script the docker file runs.

See https://github.com/mhausenblas/mkdocs-deploy-gh-pages/blob/master/action.yml

**Comment by MrManicotti** [comment]
Interesting. So when a docker run is performed in your build, that action isn't defined by you but dynamically generated by GitHub? How are you defining what environment variables you need?

**Comment by mhausenblas** [comment]
Right, seems like you're spot on @MrManicotti! Would you be up for a PR?

**Comment by MrManicotti** [comment]
Sure. Assign issue to me

**Comment by mhausenblas** [comment]
Thanks a million!

**Comment by mhausenblas** [comment]
@MrManicotti just stumbled upon https://www.innoq.com/en/blog/github-actions-automation/

**Comment by MrManicotti** [comment]
Thank you @mhausenblas ! I'll get this in sometime this weekend :)
