### ISSUE TITLE
Add support for custom domains

### ISSUE THREAD

**Issue by frealmyr** [mhausenblas/mkdocs-deploy-gh-pages#10]
Github pages supports custom domains by providing a CNAME file with a FQDN value on the root directory of the branch.

Using this action with custom domains, one would need to re-add the CNAME file each time the action runs, as this it does not persist.

It would be great to have a option for setting the custom domain in the .yml, which would generate the CNAME file on build.

**Comment by mhausenblas** [comment]
Agreed! That's an awesome suggestion @frealmyr! Any idea how to achieve this best? Maybe even a PR?

**Comment by frealmyr** [comment]
After some digging, i found out that MkDocs supported the CNAME file if you place it inside the `docs_dir`. So the support was already there. 🙈

I created a PR with the option for convenience, so that i can keep the /docs folder free of a CNAME file in my repository.

**Comment by mhausenblas** [comment]
Awesome! Yeah it does indeed support it [natively](https://www.mkdocs.org/user-guide/deploying-your-docs/) … I thought you meant something beyond that. Great we're on the same page now and will have a look at #11 shortly! Thanks a lot @frealmyr :)
