### ISSUE TITLE
always in strict mode?

### ISSUE THREAD

**Issue by jtuttas** [mhausenblas/mkdocs-deploy-gh-pages#150]
Hello, I just try you action, but the run abort with the message:

WARNING  -  Documentation file 'Beispiel2.md' contains a link to 'docs/images/test.svg' which is not found in the documentation files.
WARNING  -  Documentation file 'Beispiel2.md' contains a link to 'docs/tier.uxf.svg' which is not found in the documentation files.

Aborted with 2 warnings in strict mode!

But in my mkdocs.yml I disbaled the strict mode...

```yml
site_name: MyTest

strict: false

nav:
    - Home: bsp.md```

**Comment by jtuttas** [comment]
Any Help for this issue?

**Comment by dalonsoa** [comment]
Same here. `strict: false` in the config seems to be ignored. I can see the point on having it enabled by default, but it should be possible to manually overwrite that behaviour with the config.

**Comment by dalonsoa** [comment]
The issue seems to be here, where the information in the config file is overwritten... :(

https://github.com/mhausenblas/mkdocs-deploy-gh-pages/blob/19d5a44e72e4d7cfc7792eb67b95c15edb64d774/action.sh#L43

**Comment by mhausenblas** [comment]
PR appreciated if anyone has the cycles

**Comment by dalonsoa** [comment]
Oh, I can certainly do it - it is a one line change! The question is to know the rationale for forcing the strict mode and to be aware that his might be a breaking change.
