### ISSUE TITLE
Add support for Pymdown-extensions 7.0

### ISSUE THREAD

**Issue by runningcode** [mhausenblas/mkdocs-deploy-gh-pages#18]
When adding `pymdown-extension==7.0` to `requirements.txt`, I get the following error:
```
ERROR: mkdocs-material 4.6.0 has requirement pymdown-extensions<6.3,>=6.2, but you'll have pymdown-extensions 7.0 which is incompatible.
ERROR: pymdown-extensions 7.0 has requirement Markdown>=3.2, but you'll have markdown 3.1.1 which is incompatible.
```

For reference, I would like to use pymdownx.tabbed. a new feature in 7.0.

**Comment by runningcode** [comment]
Actually, I think this would work by default if the current version of the repo were released :)

**Comment by mhausenblas** [comment]
I just cut [1.12](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/releases/tag/1.12), wanna give it a try?

**Comment by runningcode** [comment]
Just tested. It is fixed. Thank you very much!
