### ISSUE TITLE
Update description on use of GITHUB_TOKEN

### ISSUE THREAD

**Issue by MichaelCurrin** [mhausenblas/mkdocs-deploy-gh-pages#20]
There is a note in README.md

> This action supports building and deploying with a GITHUB_TOKEN but it has problems deploying to public repositories. In public repositories, your changes will be pushed to the gh-pages branch, but an automatic build will not be performed by GitHub Pages.

Can I suggest this be updated? I don't think it's relevant anymore.

I have a public repo which auto deploys using GH actions and `GITHUB_TOKEN`.

- https://github.com/MichaelCurrin/mkdocs-quickstart/deployments

[workflow](https://github.com/MichaelCurrin/mkdocs-quickstart/blob/master/.github/workflows/main.yml)

Relates to #1

**Comment by MichaelCurrin** [comment]
On the _initial_ deploy, one has to go into Github Pages under settings to switch to `master` and back to `gh-pages` and then the environment gets setup correctly going forwards.

**Comment by mhausenblas** [comment]
Excellent catch, thanks @MichaelCurrin! Would you mind to send in a PR with the suggested wording?

**Comment by MichaelCurrin** [comment]
Sure, will do.

**Comment by MichaelCurrin** [comment]
Sorry about the delay. Am still going to do this

**Comment by MichaelCurrin** [comment]
Please see #22
