### ISSUE TITLE
Allow builds without Material Theme

### ISSUE THREAD

**Issue by MichaelCurrin** [mhausenblas/mkdocs-deploy-gh-pages#39]
When I upgraded from `1.14` to `1.15` of this action, I found that the action doesn't accept use of the builtin themes any longer. (`theme: readthedocs` or `theme: mkdocs`).

### Add to the docs

It would be great if this limitation was documented at the top of the README.md - that not only does the action supply material, but you _must_ use material. Perhaps some other custom themes work, but the builtin themes don't work and this is no point in try to install them since they are in the code of mkdocs itself.

And maybe say that if one wants to use another theme like the builtins, then that can work if one uses the action setup as `mhausenblas/mkdocs-deploy-gh-pages@1.14` where it still works.

### Add support

This may not be worthwhile for you if you only want to support Material.

And it might be beyond your control.

But it could be nice for other users if `@master` of this action supported using a builtin theme.

The reason why I say it is beyond your control is that the docker image version changed between tag versions and so the code is obscured from the action. See files changed between tags: https://github.com/mhausenblas/mkdocs-deploy-gh-pages/compare/1.14...1.15

**Comment by MichaelCurrin** [comment]
## Testing

See my notes explaining how the failure happened.

My config was setup like [this](https://github.com/MichaelCurrin/mkdocs-quickstart/blob/286e8c6f0dbab63a2d84cf7f5292cc9c9365da55/mkdocs.yml)

```yaml
theme: readthedocs
```

When I upgraded the version in this commit [286e8c6](https://github.com/MichaelCurrin/mkdocs-quickstart/commit/286e8c6f0dbab63a2d84cf7f5292cc9c9365da55), that changed my build from failing to passing - [action runs](https://github.com/MichaelCurrin/mkdocs-quickstart/actions).

Here is another way to show the error.

I also forked the template repo. I ran a using `@master` of the action which passed. When I switched from material to readthedocs in this [commit](https://github.com/MichaelCurrin/mkdocs-template/commit/be91ee0f4ef9d2866819c5c1f5f55909c49a226b) then the build failed.

[action runs](https://github.com/MichaelCurrin/mkdocs-template/actions)

**Comment by MichaelCurrin** [comment]
## Alternative

My need is just to use a builtin theme and not Material so I decided to setup a flow that doesn't rely on this action anymore and doesn't use any action specific to MkDocs or GH Pages.

Here is my workflow.

https://github.com/MichaelCurrin/mkdocs-quickstart/blob/master/.github/workflows/docs.yml

It sets up a Python environment and dependencies.

The last step uses `Makefile` and equates to this:

```
mkdocs gh-deploy --strict
```

And fortunately that works smoothly.

**Comment by squidfunk** [comment]
Author of Material for MkDocs here - the built in themes are no longer packaged with the official Docker image, which seems to be the base image of this project.

**Comment by MichaelCurrin** [comment]
Thanks. I guess that was the case from tag diff.

Then it would be sufficient to just add a note on this action's docs that this is a limitation of the action because of the underlying image.

**Comment by mhausenblas** [comment]
Thanks for raising this issue @MichaelCurrin and thanks for your input @squidfunk much appreciated (also, thanks for Material, awesome work!). I wonder what would be the best way forward in terms of not breaking people's flow and being flexible, going forward?

**Comment by squidfunk** [comment]
My advice would be not to extend from Material's Docker image. It's a Docker image tailored to Material for MkDocs after all. We removed the default themes to save on image size, which resulted in a drop from 77MB -> 62 MB, i.e. ~20%. As the Docker image is often used in CI/CD, it helps to cut build time by a few seconds.

**Comment by janoszen** [comment]
@mhausenblas I'm sorry to say, but the workflow was already broken for me. When relying on the latest version of this action you are also pulling in the latest material. They had breaking changes in their configuration format. I wouldn't worry about it too much.

**Comment by mhausenblas** [comment]
That's a fair point @janoszen. Still wondering what to do about it. Freeze on v5?

**Comment by janoszen** [comment]
I froze the github action on a specific version when it broke... you could also maintain separate tags for material and non-material if that's not too much work.

**Comment by mhausenblas** [comment]
> I froze the github action on a specific version when it broke... you could also maintain separate tags for material and non-material if that's not too much work.

I like that @janoszen. Can I interest you in sending in a PR to kick off the work?

BTW, best wishes to Sanja. Small world …

**Comment by janoszen** [comment]
Sure thing, give me a few days.

**Comment by mhausenblas** [comment]
Awesome, thank you @janoszen and happy to give you also more access to the repo if that helps?

**Comment by janoszen** [comment]
@mhausenblas sounds good. I'll prep it in a fork and then you can review it before we merge.

**Comment by janoszen** [comment]
@mhausenblas I have created a version without material that works fine with material too as long as you have a `requirements.txt` file. You can try it out by using the action name `janoszen/mkdocs-deploy-gh-pages@nomaterial` in your builds.

**Comment by mhausenblas** [comment]
Thanks a lot and could you PR the repo pls @janoszen?

**Comment by janoszen** [comment]
Sure, master or a `nomaterial` branch?

**Comment by mhausenblas** [comment]
Yeah, a dedicated branch like `nomaterial` sounds good. This also reminds me to finally move from `master` to `main` as well, thanks!

**Comment by janoszen** [comment]
@MichaelCurrin this issue is now resolved. You can use `mhausenblas/mkdocs-deploy-gh-pages@nomaterial` instead of `mhausenblas/mkdocs-deploy-gh-pages@master` to build without material design. You will have to provide a `requirements.txt` with the required dependencies.
