### ISSUE TITLE
Missing requirements.txt?

### ISSUE THREAD

**Issue by berniedurfee** [mhausenblas/mkdocs-deploy-gh-pages#5]
As of version 1.10. the action fails unless there's a `requirements.txt` file in the root of the deployed project. I don't think this is a requirement for mkdocs.

I think the fix is either to document that you _must_ have a `requirements.txt` file in the root of the project or put an `if` around the `pip install` command in the `action.sh` file. I'm not sure what your intent is though.

Here's the error:

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/github/workspace/requirements.txt'`

**Comment by mhausenblas** [comment]
Thanks for reporting! Hmmmm, I thought we fixed that … any idea @oxr463 ?

**Comment by mhausenblas** [comment]
Thanks a lot for the fix @oxr463 and can you try again with `v1.11` please @berniedurfee?

**Comment by mhausenblas** [comment]
Thanks a lot for the fix @oxr463 and can you try again with `v1.11` please @berniedurfee?
