### ISSUE TITLE
how to create gh-pages branch

### ISSUE THREAD

**Issue by epogrebnyak** [mhausenblas/mkdocs-deploy-gh-pages#51]
I've been using your script in several projects, but when templating a new one I cannot recall how to make `gh-pages` branch/ 

Should I create it manually? After running the script it is not created, I get README.md displayed in my gtihub.io page.

this is probably very silly situation and should have a simple answer that I do not see.

**Comment by epogrebnyak** [comment]
This seems branch renaming issue:

https://github.com/epogrebnyak/aloh3/blob/95d2cd586e337adb4c140db519334b06cbfda735/.github/workflows/main.yml#L5

**Comment by mhausenblas** [comment]
Try again pls, just merged a pending PR.

**Comment by epogrebnyak** [comment]
The problem for me was not an Actions scripts, but a template:

https://github.com/mhausenblas/mkdocs-template/blob/06e49c47bf485df16ec3f603e20717e8f4ce61bf/.github/workflows/main.yml#L5

**Comment by epogrebnyak** [comment]
Just to note, the release pipeline works fine.

**Comment by mhausenblas** [comment]
Ok, thanks, so we can close this issue?

**Comment by epogrebnyak** [comment]
I can make a PR towards template repo, change master to main there, that should help

Here I close, thank you for prompt response!
