### ISSUE TITLE
Can't use this with mkdocs-minify-plugin>=0.2.3

### ISSUE THREAD

**Issue by RammusXu** [mhausenblas/mkdocs-deploy-gh-pages#7]
It will shows error when my requirements.txt contains `mkdocs-minify-plugin>=0.2.3`
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/mkdocs_minify_plugin-0.2.1-py3.6.egg'
##[error]Docker run failed with exit code 1
```

[more info](https://github.com/RammusXu/toolkit/runs/445353435?check_suite_focus=true)

**Comment by mhausenblas** [comment]
Hmmm, not sure why it's failing. Need to reproduce …

**Comment by RammusXu** [comment]
I move to mkdocs-material 5. I think it's fine now.
